version: '3.9'

services:
  service1:
    build: ./nodets-boilerplate
    networks:
      - my_network
    deploy:
      replicas: 3  # Ensure three instances
    restart: always

  service2:
    build: ./docker
    ports:
      - "8080"  # Optional internal port
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "8198:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./web:/usr/share/nginx/html
    networks:
      - my_network
    depends_on:
      - service1

networks:
  my_network:
